app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [

    path('', views.home, name='home'),
    path('charts/user-review/', views.UserReviewChartView.as_view(), name='chart-users'),
    path('charts/genre/', views.GenreChartView.as_view(), name='chart-genre'),
    path('charts/anime-review/', views.AnimeReviewChartView.as_view(), name='chart-anime'),
    path('anime/new/', views.newAnime, name='new-anime')
]

django-db-analytics/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

app_name = 'app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('app.urls'))
]

django_db_analytics/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

class User(models.Model):
    email = models.CharField(unique=True, max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'users'

class Anime(models.Model):
    title = models.CharField(max_length=100)
    episodes = models.IntegerField(default=1)
    genre = models.CharField(max_length=100)

    class Meta:
        db_table = 'anime'


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def date_as_string(self):
        return self.createdat.strftime('%Y-%m-%d')

    class Meta:
        db_table = 'reviews'

app/forms.py
from django.forms import ModelForm

from app.models import Review, Anime


class AnimeForm(ModelForm):

    class Meta:
        model = Anime
        fields = ['title', 'episodes', 'genre']


class ReviewForm(ModelForm):

    class Meta:
        model = Review
        fields = ['content']

app/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from django.shortcuts import render

from app.forms import AnimeForm
from app.models import User, Review, Anime


def home(req):
    return render(req, 'home.html', {'page_title': 'Home page'})


def newAnime(req):
    if req.method == 'POST':
        form = AnimeForm(req.POST)
        if form.is_valid():
            a = Anime(title=form.cleaned_data['title'], episodes=form.cleaned_data['episodes'], genre=form.cleaned_data['genre'])
            a.save()
            return redirect('app:new-anime')
        else:
            return render(req, 'newAnime.html', {'form': form})
    else:
        form = AnimeForm()
        return render(req, 'newAnime.html', {'form': form})


class GenreChartView(TemplateView):                  # broj anime po zanru chart
    template_name = 'genreChart.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        anime = Anime.objects.all()
        query_set = []
        genre_set = set()
        for a in anime:
            genre_set.add(a.genre)
        for genre in genre_set:
            number_of_anime = 0
            for a in anime:
                if len(genre) > 0 and a.genre != genre:
                    continue
                number_of_anime += 1
            query_set.append({'genre': genre, 'number_of_anime': number_of_anime})
        query_set.sort(key=lambda l: l['number_of_anime'])
        context["qs"] = query_set
        context["char_type"] = self.request.GET.get('chartType', 'bar')
        return context


class AnimeReviewChartView(TemplateView):                  # reviews po animeu u vremenskom intervalu chart
    template_name = 'animeReviewChart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre = self.request.GET.get('genre', '')
        date_from = self.request.GET.get('from', '')
        date_to = self.request.GET.get('to', '')
        anime = Anime.objects.all()
        reviews = Review.objects.all()
        query_set = []
        for a in anime:
            number_of_reviews = 0
            for review in reviews:
                if len(genre) > 0 and anime.genre != genre:
                    continue
                if len(date_from) > 0 and review.created_at < date_from:
                    continue
                if len(date_to) > 0 and review.created_at > date_to:
                    continue
                if review.anime == a.title:
                    number_of_reviews += 1
            query_set.append({'anime': a.title, 'number_of_reviews': number_of_reviews})
        query_set.sort(key=lambda l: l['number_of_reviews'])
        context["qs"] = query_set
        context["char_type"] = self.request.GET.get('chartType', 'bar')
        return context


class UserReviewChartView(TemplateView):                    # reviews po korisniku u vremenskom intervalu
    template_name = 'userReviewChart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_from = self.request.GET.get('from', '')
        date_to = self.request.GET.get('to', '')
        reviews = Review.objects.all()
        users = User.objects.all()
        query_set = []
        for user in users:
            number_of_reviews = 0
            for review in reviews:
                if len(user.email) > 0 and review.user != user.email:
                    continue
                if len(date_from) > 0 and review.created_at < date_from:
                    continue
                if len(date_to) > 0 and review.created_at > date_to:
                    continue
                number_of_reviews += 1
            if number_of_reviews > 0:
                query_set.append({'user': user.email, 'number_of_reviews': number_of_reviews})
        query_set.sort(key=lambda a: a['number_of_reviews'])
        context["qs"] = query_set
        context["char_type"] = self.request.GET.get('chartType', 'bar')
        return context

app/templates/animeReviewChart.html
{% block title %}
    Popularity analytics
{% endblock title %}

{% block content %}
    Anime popularity analytics - Reviews per anime entry in a specified date interval
    <canvas id="myChart" width="400" height="170"></canvas>
{% endblock content %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<script>
$(document).ready(function () {
    const ctx = document.getElementById('myChart').getContext('2d');
    alert('paaaa')
    const myChart = new Chart(ctx, {
        type: '{{char_type}}',
        data: {
            labels: [{% for item in qs %}'{{item.anime}}',{% endfor %}],
            datasets: [{
                label: '# of Reviews',
                data: [{% for item in qs %}{{item.number_of_reviews}},{% endfor %}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

app/templates/edit.html
{% extends 'global/master.html' %}

{% block title %}
    Edit trip
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'app:edit' id %}">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.destination.id_for_label }}">{{ form.destination.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.destination.id_for_label }}" name="{{ form.destination.name }}" value="{{ form.destination.value }}">
            {% if form.destination.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.destination.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.date.id_for_label }}">{{ form.date.label_tag }}</label>
            <input type="date" class="form-control" id="{{ form.date.id_for_label }}" name="{{ form.date.name }}" value="{{ form.date.value }}">
            {% if form.date.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.date.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.cost.id_for_label }}">{{ form.cost.label_tag }}</label>
            <input type="number" class="form-control" id="{{ form.cost.id_for_label }}" name="{{ form.cost.name }}" value="{{ form.cost.value }}">
            {% if form.cost.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.cost.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.travel_agency.id_for_label }}">{{ form.travel_agency.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.travel_agency.id_for_label }}" name="{{ form.travel_agency.name }}" value="{{ form.travel_agency.value }}">
            {% if form.travel_agency.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.travel_agency.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.num_travellers.id_for_label }}">{{ form.num_travellers.label_tag }}</label>
            <input type="number" class="form-control" id="{{ form.num_travellers.id_for_label }}" name="{{ form.num_travellers.name }}" value="{{ form.num_travellers.value }}">
            {% if form.num_travellers.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.num_travellers.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>


{% endblock %}

app/templates/genreChart.html
{% block title %}
    Genre analytics
{% endblock title %}


{% block content %}
    Genre analytics - Frequency of genres within all listed anime
    <canvas id="myChart" width="200" height="90"></canvas>
{% endblock content %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<script>
$(document).ready( function () {
    const ctx = document.getElementById('myChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: '{{char_type}}',
        data: {
            labels: [{% for item in qs %}'{{item.genre}}',{% endfor %}],
            datasets: [{
                label: '# of Reviews',
                data: [{% for item in qs %}{{item.number_of_anime}},{% endfor %}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

app/templates/global/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app:home' %}">
        <img src="{% static 'img/animelist.jfif' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
        Anime List
    </a>

</nav>

app/templates/global/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'global/header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>

app/templates/home.html
{%  extends 'global/master.html' %}

{% block content %}
    <div class="list-group">
    <a href="{% url 'app:new-anime' %}">
        <span class="badge badge-primary">Add new anime</span>
    </a>
    </div>
    <div class="col-5">
        <h1>Genre analytics</h1>
        <p>Frequency of a certain genre within all listed anime</p>

        <form action="{% url 'app:chart-genre' %}" method="get" class="col-6">
            <div class="form-group">
                <label for="inputStateAnime">Type of chart:</label>
                <select id="inputStateAnime" class="form-control" name="chartType">
                    <option selected>bar</option>
                    <option>line</option>
                    <option>radar</option>
                    <option>bubble</option>
                    <option>scatter</option>
                </select>
            </div>
          <button type="submit" class="btn btn-primary">Analyze</button>
        </form>
        <br><br><br>
    </div>

    <div class="col-5">
        <h1>Anime popularity analytics</h1>
        <p>Reviews per anime entry in a specified date interval</p>

        <form action="{% url 'app:chart-anime' %}" method="get" class="col-6">
            <div class="form-group">
                <label for="inputStateReview">Type of chart:</label>
                <select id="inputStateReview" class="form-control" name="chartType">
                    <option selected>bar</option>
                    <option>line</option>
                    <option>radar</option>
                    <option>bubble</option>
                    <option>scatter</option>
                </select>
            </div>
          <div class="form-group">
            <label for="genrePosts">Genre</label>
            <input type="text" class="form-control" id="genrePosts" name="genre" placeholder="">
          </div>
          <div class="form-group">
            <label for="dateFromPost">Date From</label>
            <input type="date" class="form-control" id="dateFromPost" name="from" placeholder="From">
          </div>
          <div class="form-group">
            <label for="dateToPost">Date To</label>
            <input type="date" class="form-control" id="dateToPost" name="to" placeholder="To">
          </div>
            <br>
          <button type="submit" class="btn btn-primary">Analyze</button>
        </form>
        <br><br><br>
    </div>

    <div class="col-5">
        <h1>User analytics</h1>
        <p>Users review activity in a specified date interval</p>

        <form action="{% url 'app:chart-users' %}" method="get" class="col-6">
            <div class="form-group">
                <label for="inputStateUser">Type of chart:</label>
                <select id="inputStateUser" class="form-control" name="chartType">
                    <option selected>bar</option>
                    <option>line</option>
                    <option>radar</option>
                    <option>bubble</option>
                    <option>scatter</option>
                </select>
            </div>
          <div class="form-group">
            <label for="dateFromPost">Date From</label>
            <input type="date" class="form-control" id="dateFromPost" name="from" placeholder="Date From">
          </div>
          <div class="form-group">
            <label for="dateToPost">Date To</label>
            <input type="date" class="form-control" id="dateToPost" name="to" placeholder="Date To">
          </div>
          <button type="submit" class="btn btn-primary">Analyze</button>
        </form>
        <br><br><br>
    </div>
{% endblock content %}

app/templates/newAnime.html
{% extends 'global/master.html' %}

{% block title %}
    Add new anime
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'app:new-anime' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.episodes.id_for_label }}">{{ form.episodes.label_tag }}</label>
            <input type="number" class="form-control" id="{{ form.episodes.id_for_label }}" name="{{ form.episodes.name }}">
            {% if form.episodes.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.episodes.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.genre.id_for_label }}">{{ form.genre.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.genre.id_for_label }}" name="{{ form.genre.name }}">
            {% if form.genre.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.genre.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>


        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

app/templates/trip.html
{% extends 'global/master.html' %}

{% block title %}
    trip.destination
{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ trip.destination }}
                {% if perms.app.change_trip %}
                    <a href="{% url 'app:edit' trip.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                {% endif %}
                {% if perms.app.delete_trip %}
                    <a href="{% url 'app:delete' trip.id %}">
                        <span class="badge badge-primary">Delete</span>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>Date: {{ trip.date }}</p>
                <p>Cost: {{ trip.cost }}.00$</p>
                <p>Number of travellers who attended: {{ trip.num_travellers }}</p>

                <a href="{% url 'app:trip_entries' trip.id %}">
                    <span class="badge badge-primary">See diary entries</span>
                </a>

                {% if perms.app.add_entry %}
                    <a href="{% url 'app:new_entry' id=trip.id %}">
                        <span class="badge badge-primary">Add diary entry</span>
                    </a>
                {% endif %}
                <footer class="blockquote-footer">
                    Agency:
                    <cite title="Source Title">
                        {{ trip.travel_agency }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>

{% endblock %}

app/templates/trips.html
{%  extends 'global/master.html' %}

{% block title %}
    Trips
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for trip in trips %}
            <a class="list-group-item list-group-item-action" href="{% url 'app:trip' trip.id %}">
                {{ trip.destination }}
            </a>
            <br>
        {% endfor %}
        {% if perms.app.add_trip %}
                    <a href="{% url 'app:new' %}">
                        <span class="badge badge-primary">Add new trip</span>
                    </a>
        {% endif %}
    </div>
{% endblock %}

app/templates/userReviewChart.html
{% block title %}
    User analytics - User review activity in a specified date interval
{% endblock title %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
$(document).ready(function () {
    const ctx = document.getElementById('myChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: '{{char_type}}',
        data: {
            labels: [{% for item in qs %}'{{item.user}}',{% endfor %}],
            datasets: [{
                label: '# of Reviews',
                data: [{% for item in qs %}{{item.number_of_reviews}},{% endfor %}],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

{% block content %}
    <canvas id="myChart" width="200" height="90"></canvas>
{% endblock content %}